### ISSUE TITLE
Would be nice to remove the dependency on conda. 

### ISSUE THREAD

**Issue by Uncle-Enzo** [AkshitIreddy/CUPCAKEAGI#1]
And have the instructions as to where the requirements file is updated in the guide and remove all local dependencies in the file.

Looks a very interesting project :)

**Comment by AkshitIreddy** [comment]
i've updated the readme with requirements.txt file location

**Comment by AkshitIreddy** [comment]
conda environment is needed because it needs an isolated environment for installing python packages for the python scripts it generates, i'll add code that cleans the environment every 2 days so that it doesn't get bloated.

**Comment by AkshitIreddy** [comment]
i've updated the requirements.txt file

**Comment by Uncle-Enzo** [comment]
Thanks for the update.
