### ISSUE TITLE
Typo in mental_simulation.py, line 46

### ISSUE THREAD

**Issue by JulesRoland** [AkshitIreddy/CUPCAKEAGI#2]
mental_simulation.py

Line 46 reads:

    personality = "Peronsality:\n" + open(os.path.join(STATE_DIR, "personality.txt")).read() 

It should say:

    personality = "Personality:\n" + open(os.path.join(STATE_DIR, "personality.txt")).read() 

dream.py

Line 81 reads:

    personality = "Peronsality:\n" + open(os.path.join(STATE_DIR, "personality.txt")).read() 
It should say:

    personality = "Personality:\n" + open(os.path.join(STATE_DIR, "personality.txt")).read()

**Comment by AkshitIreddy** [comment]
oh yeah, i'll fix that

**Comment by AkshitIreddy** [comment]
okay, i fixed the typo, thanks for pointing it out🙂
