### ISSUE TITLE
Expose APIs on local/cloud using langchain-serve?

### ISSUE THREAD

**Issue by deepankarm** [AkshitIreddy/CUPCAKEAGI#3]
Github repo - https://github.com/jina-ai/langchain-serve

**Benefits**

- Exposes APIs from function definitions locally as well as on the cloud.
- Very few lines of code changes, ease of development remains the same as local.
- Supports both REST & Websocket endpoints
- Serverless/autoscaling endpoints with automatic tls certs.
- Real-time streaming, human-in-the-loop support

**Comment by AkshitIreddy** [comment]
cool, i'll check it out, i haven't used langchain-serve before though so i'll need a while to learn it, right now cupcakeagi uses fastapi

**Comment by deepankarm** [comment]
@AkshitIreddy Even langchain-serve uses FastAPI (and Jina) to expose API locally and it is simply adding `@serving` decorator to the function that you want to expose.
