### ISSUE TITLE
Keys + GPT-4

### ISSUE THREAD

**Issue by daffi7** [AkshitIreddy/CUPCAKEAGI#6]
Hi, 
where do I enter the keys? 
And can it be made to use GPT-4? (I DO have access to GPT-4 through API)

**Comment by AkshitIreddy** [comment]
you'll have to enter the keys in .env file which is present in  backend/Multi-Sensory Virtual AAGI

**Comment by AkshitIreddy** [comment]
to use gpt4 you'll have to modify the lines that initialize the model
ChatOpenAI(model='gpt-3.5-turbo') # switch to 'gpt-4'
